# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138834M6FvEIypzgLHZLOm5SgCcWh1Ary
"""

!pip install strands-agents strands-agents-tools tavily-python openai pydantic gradio

import os
import json
import gradio as gr
from pydantic import BaseModel
from strands import Agent
from strands.models.openai import OpenAIModel
from strands.tools import tool
from tavily import TavilyClient

# --- 1. Hardcoded API Keys (Approach B) ---
# Paste your keys directly inside the quotes below
openrouter_key = "yOUR_API_KEY"
tavily_key = "yOUR_API_KEY"

# Set Tavily key to environment for the tool to access
os.environ["TAVILY_API_KEY"] = tavily_key

# --- Define the Output Contract ---
class LeadAnalysis(BaseModel):
    score: int
    intent_level: str
    reasoning: str
    key_signals: list[str]

# --- Main Pipeline Function ---
def build_and_run_pipeline(company_name: str):
    if not openrouter_key or openrouter_key == "YOUR_OPENROUTER_API_KEY" or not tavily_key or tavily_key == "YOUR_TAVILY_API_KEY":
        return "Error: Missing API Keys", "", {"error": "Missing Keys"}, "Please replace the placeholder strings in the code with your actual API keys."

    # Define tool inside function to ensure it uses the runtime API key
    @tool
    def web_search(query: str) -> str:
        """Searches the internet for real-time information about a company, product, or trend."""
        client = TavilyClient(api_key=os.environ["TAVILY_API_KEY"])
        response = client.search(query=query, search_depth="advanced", max_results=3)
        results = [f"Source: {res['url']}\nContent: {res['content']}" for res in response['results']]
        return "\n\n".join(results)

    # Configure the OpenRouter Model with explicit Auth and App headers
    openrouter_model = OpenAIModel(
        model_id="openrouter/free",
        client_args={
            "api_key": openrouter_key,
            "base_url": "https://openrouter.ai/api/v1",
            "default_headers": {
                "Authorization": f"Bearer {openrouter_key}",
                "HTTP-Referer": "https://colab.research.google.com/",
                "X-Title": "Colab Sales Agents"
            }
        }
    )

    # Initialize Agents
    trend_agent = Agent(
        model=openrouter_model,
        system_prompt=(
            "You are a trend analyst. Your job is to identify recent launches, "
            "GitHub activity, or social discussions (Reddit, Hacker News) about the requested company. "
            "Summarize the recent signals clearly. Do not score the lead."
        ),
        tools=[web_search]
    )

    search_agent = Agent(
        model=openrouter_model,
        system_prompt=(
            "You are a company research specialist. Find the company's size, "
            "founders, tech stack, and primary product offerings. "
            "Provide a factual, bulleted summary."
        ),
        tools=[web_search]
    )

    analysis_agent = Agent(
        model=openrouter_model,
        system_prompt=(
            "You are a senior sales analyst. Review the provided trend signals and company data. "
            "Determine the buying intent and output a structured JSON evaluation matching the LeadAnalysis schema. "
            "Score from 0-100 based on recent activity, relevance, and engagement."
        )
    )

    email_agent = Agent(
        model=openrouter_model,
        system_prompt=(
            "You are an expert B2B copywriter. Write a highly personalized, natural-sounding "
            "outreach email based strictly on the provided analysis. Mention specific recent events. "
            "Keep it under 150 words. Do not sound robotic."
        )
    )

    # Execute the Pipeline
    try:
        trend_result = trend_agent(f"Find the latest news, launches, and developer engagement for {company_name}")
        company_result = search_agent(f"Research the company {company_name}. Find their core product and tech stack.")

        analysis_prompt = f"TREND DATA:\n{trend_result}\n\nCOMPANY DATA:\n{company_result}"
        analysis_response = analysis_agent(f"{analysis_prompt}\nReturn your analysis strictly matching the requested JSON schema.")

        # Clean up JSON for the UI display
        try:
            analysis_json = json.loads(str(analysis_response))
        except:
            analysis_json = {"raw_output": str(analysis_response)}

        email_prompt = f"Draft an outreach email to the CTO of {company_name} using this analysis: {analysis_response}"
        email_result = email_agent(email_prompt)

        return str(trend_result), str(company_result), analysis_json, str(email_result)

    except Exception as e:
        return str(e), "", {"error": str(e)}, f"Pipeline failed: {e}"

# --- Gradio UI Layout ---
with gr.Blocks() as app:
    gr.Markdown("# 🚀 Multi-Agent Sales Intelligence Pipeline")
    gr.Markdown("Enter a company name below to trigger the agent workflow. The system will hunt for trends, gather company context, score the lead, and draft personalized outreach.")

    with gr.Row():
        with gr.Column(scale=1):
            company_input = gr.Textbox(label="Target Company Name", placeholder="e.g., LangChain, Stripe")
            submit_btn = gr.Button("Run Discovery Pipeline", variant="primary")

        with gr.Column(scale=2):
            email_output = gr.Textbox(label="Final Output: Personalized Email", lines=10)

    with gr.Accordion("🔍 View Intermediate Agent Reasoning", open=False):
        gr.Markdown("Expand this section to see exactly what each specialized agent found and how the lead was scored before the email was drafted.")
        with gr.Row():
            trend_output = gr.Textbox(label="1. Trend Agent Output", lines=8)
            search_output = gr.Textbox(label="2. Search Agent Output", lines=8)
        analysis_output = gr.JSON(label="3. Analysis Agent Output (Structured Data)")

    # Wire up the button
    submit_btn.click(
        fn=build_and_run_pipeline,
        inputs=[company_input],
        outputs=[trend_output, search_output, analysis_output, email_output]
    )

# Launch with theme applied in Gradio 6.0 format
app.launch(debug=True, share=True, theme=gr.themes.Soft())

